data = [
	{
		"S_no":"1",
		"timestamp": '2022-11-14T08:34:22.229Z',
		"name": 'Aaryansh Pathak',
		"year": '2nd',
		"vertical": 'Video editor',
		"linkedinProfile": 'https://www.linkedin.com/in/aaryansh-pathak-424786241',
		"instagramProfile":
			'https://www.instagram.com/invites/contact/?i=dryk86n0rpd7&utm_content=10i9v6w',
		"photo": 'https://drive.google.com/uc?export=view&id=1eDAfhchaJu1ri3WupNOW3f68Ljlkh9aB',
	},
	{	
		"S_no":"2",
		"timestamp": '2022-11-14T09:36:03.360Z',
		"name": 'Akhilendra Pratap',
		"year": '2nd',
		"vertical": 'Web Developer',
		"linkedinProfile": 'https://www.linkedin.com/in/akhilendrapratap',
		"instagramProfile": 'https://www.instagram.com/akhilendra_11/',
		"twitterProfile": 'https://twitter.com/Akhilendra112',
		"githubProfile": 'https://github.com/Akhilendra01',
		"photo": 'https://drive.google.com/uc?export=view&id=1AkO-b4Tw3qLmHqgHe3sU_RBTZLq3OLhs',
	},
	{	
		"S_no":"3",
		"timestamp": '2022-11-13T14:39:26.439Z',
		"name": 'Akshat Maheshwari',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/akshat-maheshwari-b5846b222',
		"instagramProfile": 'https://instagram.com/akrules03?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100083009631092',
		"twitterProfile":
			'https://twitter.com/Akrules03?s=20&t=WH0JqQnvrEnNd3MI1Dbp2Q',
		"githubProfile": 'github.com/akrules03',
		"photo": 'https://drive.google.com/uc?export=view&id=1ehSxZt6zBYEfmZYNS8lD-ja4zUZunWWj',
	},
	{
		"S_no":"4",
		"timestamp": '2022-11-13T14:09:16.582Z',
		"name": 'Akshit Sharma',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'linkedin.com/in/akshit-sharma-b70610223',
		"instagramProfile": 'https://www.instagram.com/akshittsharmaa/',
		"twitterProfile": 'https://twitter.com/AkshittSharmaa',
		"photo": 'https://drive.google.com/uc?export=view&id=1jk74pggA_EurkTRbntSrEJFtJBzSg-iX',
	},
	{
		"S_no":"5",
		"timestamp": '2022-11-13T17:58:54.923Z',
		"name": 'Aniket Mishra',
		"year": '2nd',
		"vertical": 'Video Editor',
		"linkedinProfile": 'https://www.linkedin.com/in/aniket-mishra-721370129',
		"photo": 'https://drive.google.com/uc?export=view&id=1O3NUi7wcNsdrosiDZdh2ID7TKIkYnWvz',
	},
	{
		"S_no":"6",
		"timestamp": '2022-11-13T10:54:30.168Z',
		"name": 'Anjaneya Dwivedi',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/anjaneya-dwivedi-0b755a201',
		"photo": '../assets/team_img/Team__Download/anjaney.jpeg',
	},
	{
		"S_no":"7",
		"timestamp": '2022-11-13T15:45:53.727Z',
		"name": 'Anmol Singh',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'http://linkedin.com/in/anmol-singh-b094b3244',
		"instagramProfile": 'https://instagram.com/anmol12_singh?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100076607132656',
		"photo": 'https://drive.google.com/uc?export=view&id=1wtMbguaiKrTYXTvdSqQWLPO0tUS49W4h',
	},
	{
		"S_no":"8",
		"timestamp": '2022-11-13T11:03:22.476Z',
		"name": 'Anshika Arjariya ',
		"year": '2nd',
		"vertical": 'Content Writer',
		"linkedinProfile": 'https://www.linkedin.com/in/anshika-arjariya-18a911244',
		"instagramProfile": 'anshikaarjariya ',
		"photo": 'https://drive.google.com/uc?export=view&id=14oO3CclkMWWNBuhyjwbJGKw3Gcm1pL_C',
	},
	{
		"S_no":"9",
		"timestamp": '2022-11-13T16:34:25.128Z',
		"name": 'Anurag Soni',
		"year": '2nd',
		"vertical": 'Graphic Designer',
		"linkedinProfile": 'Anurag Soni',
		"instagramProfile": 'anuragsoni.as',
		"photo": '../assets/team_img/Team__Download/anurag.jpeg',
	},
	{
		"S_no":"10",
		"name": 'Gautam Pratap',
		"year": '2nd',
		"vertical": 'Graphic Designer',
		"linkedinProfile": 'https://www.linkedin.com/in/gautampratap',
		"instagramProfile": 'https://www.instagram.com/yoursgautampratap/',
		"photo": '../assets/team_img/Team__Download/gautum.jpg',
	},
	{
		"S_no":"11",
		"timestamp": '2022-11-13T18:19:21.830Z',
		"name": 'Arin Bansal',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile":
			'https://www.google.com/url?sa=t&source=web&rct=j&url=https://in.linkedin.com/in/arin-bansal-46109a227&ved=2ahUKEwjxyNCB4qv7AhVw7TgGHTQdCnEQjjh6BAgUEAE&usg=AOvVaw3QKYbeCVAnvYA9rNuIP4in',
		"instagramProfile":
			'https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.instagram.com/arin_bansal/%3Fhl%3Den&ved=2ahUKEwij25mW4qv7AhW9xTgGHXJZC8QQFnoECBYQAQ&usg=AOvVaw2Sv8ANIjxM9RjZoLlLIaZu',
		"photo": 'https://drive.google.com/uc?export=view&id=1xlhhNeVKQStKtXoF5YLR0gnNdAG2N888',
	},
	{	
		"S_no":"12",
		"timestamp": '2022-11-13T14:25:21.297Z',
		"name": 'Arnika Chaturvedi',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/arnika-chaturvedi-03444a237',
		"instagramProfile":
			'https://instagram.com/arnika_chaturvedi?igshid=YmMyMTA2M2Y=',
		"photo": 'https://drive.google.com/uc?export=view&id=1vKh7ZfK8V1l0h4W8P0bkauESlaFtVgFs',
	},
	{	
		"S_no":"13",
		"timestamp": '2022-11-14T09:37:31.675Z',
		"name": 'Arpit Gupta',
		"year": '2nd',
		"vertical": 'Photographer ',
		"linkedinProfile": 'https://www.linkedin.com/in/arpit-gupta-24170b238',
		"instagramProfile": 'https://instagram.com/_.arpit_.01?igshid=YmMyMTA2M2Y=',
		"twitterProfile":
			'https://twitter.com/ArpitGu72813231?t=-cS7mVb-Mlj78fK2e9zrYw&s=09',
		"photo": 'https://drive.google.com/uc?export=view&id=1jQF59iYZ1rFPr-GKfKwzl-2ZnzRs3FCA',
	},
	{	
		"S_no":"14",
		"timestamp": '2022-11-13T17:32:14.725Z',
		"name": 'Ashay Jain ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/ashay-jain-485a43244',
		"instagramProfile": 'easyyy_10',
		"photo": '../assets/team_img/ashay.jpg',
	},
	{
		"S_no":"15",
		"timestamp": '2022-11-13T14:24:02.901Z',
		"name": 'Asmita Jain',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/asmita-jain-a20343239',
		"instagramProfile": 'https://instagram.com/asmita_jain03?igshid=YmMyMTA2M2Y=',
		"photo": 'https://drive.google.com/uc?export=view&id=1ZjvVtVL8L2v8jAdAObypLlVZsxcAmgvX',
	},
	{	
		"S_no":"16",
		"timestamp": '2022-11-13T12:05:46.160Z',
		"name": 'Ayushi Verma ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/ayushi-verma-318a10244',
		"instagramProfile": 'https://instagram.com/ayushiii_v?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100083007799113',
		"photo": 'https://drive.google.com/uc?export=view&id=1OGLaVQ7APqUmiZxW8t-r55d_wvHxMZrX',
	},
	{	
		"S_no":"17",
		"timestamp": '2022-11-13T14:05:55.377Z',
		"name": 'Bharat Verma ',
		"year": '2nd',
		"vertical": 'Executive and Content Writer ',
		"linkedinProfile": 'https://www.linkedin.com/in/bharat-verma-385284243',
		"instagramProfile": 'https://instagram.com/cheeee_ku?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100032990748860',
		"photo": '../assets/team_img/Team__Download/bharat.jpg',
	},
	{
		"S_no":"18",
		"timestamp": '2022-11-13T10:36:43.379Z',
		"name": 'Bhumika Chouhan',
		"year": '2nd',
		"vertical": 'Executive and Content writer ',
		"linkedinProfile": 'https://www.linkedin.com/in/bhumika-chouhan-237906237',
		"photo": 'https://drive.google.com/uc?export=view&id=1avHA3CHkP0I7mkMkLwNaystx_s41aYY1',
	},
	{
		"S_no":"19",
		"timestamp": '2022-11-13T14:24:19.693Z',
		"name": 'Disha Badetia',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/disha-badetia-337aa3242/',
		"instagramProfile": 'https://www.instagram.com/disha.1574/',
		"photo": 'https://drive.google.com/uc?export=view&id=1QkEsrtI8-dbCTORr8JcgPm4IjVFRbRug',
	},
	{
		"S_no":"20",
		"timestamp": '2022-11-14T10:39:04.008Z',
		"name": 'Jayant Dhakad',
		"year": '2nd',
		"vertical": 'Web Developer',
		"linkedinProfile": 'https://www.linkedin.com/in/jayant-dhakad-8a5517233/',
		"instagramProfile": 'https://www.instagram.com/jayant_dhakad.1/',
		"githubProfile": 'https://github.com/jake8989',
		"photo": 'https://drive.google.com/uc?export=view&id=1zl6VlaMgD7QmY5GNiiJEQL7qJq8LjrQM',
	},
	{
		"S_no":"21",
		"timestamp": '2022-11-13T10:00:11.868Z',
		"name": 'Kartik Tiwari',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/kartik-tiwari-954b54244',
		"githubProfile": 'Kartik79',
		"photo": 'https://drive.google.com/uc?export=view&id=1lqUcOANVgHQIPPIdnIVakWWQ_dt9DAZl',
	},
	{
		"S_no":"22",
		"timestamp": '2022-11-13T10:49:22.120Z',
		"name": 'Kartikeya Mande',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/kartikeya-mande-a5a006225',
		"instagramProfile":
			'https://instagram.com/kartikeyamande19?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/kartikeya.mande',
		"githubProfile": 'https://github.com/Kartikeya192002',
		"photo": '../assets/team_img/Team__Download/mande.jpg',
	},
	{
		"S_no":"24",
		"timestamp": '2022-11-13T18:05:24.580Z',
		"name": 'Kushagra Patel',
		"year": '2nd',
		"vertical": '"Photo"grapher',
		"linkedinProfile": 'https://www.linkedin.com/in/kushagra-patel-43185b22b',
		"instagramProfile": 'kushagra_amicable',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100086292642370',
		"twitterProfile": 'None',
		"githubProfile": 'None',
		"photo": 'https://drive.google.com/uc?export=view&id=1_h7TLeTUYgMmb8r7nAVS8KMd-b8CIlUl',
	},
	{
		"S_no":"25",
		"timestamp": '2022-11-13T16:42:29.181Z',
		"name": 'Lokesh Pawar',
		"year": '2nd',
		"vertical": 'Video Editor',
		"linkedinProfile": 'https://www.linkedin.com/in/wholokeshpawar/',
		"instagramProfile": 'https://www.instagram.com/lokesh.pawar.5/',
		"facebookProfile": 'https://www.facebook.com/lokesh.pawar.9484941/',
		"twitterProfile": 'https://mobile.twitter.com/lokeshpawar51',
		"photo": 'https://drive.google.com/uc?export=view&id=15WFPyElcyBt--uB5OJLhNQJKzQf4RSj9',
	},
	{
		"S_no":"26",
		"timestamp": '2022-11-13T17:58:57.765Z',
		"name": 'Muzaina Tauqeer',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/muzaina-tauqeer-5a263b245',
		"instagramProfile": 'muzaina_tauqeer',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100080462827438',
		"twitterProfile": '-',
		"githubProfile": '-',
		"photo": 'https://drive.google.com/uc?export=view&id=170826QDTGunpbxDICv7AWkWO3ZF0OvjB',
	},
	{
		"S_no":"27",
		"timestamp": '2022-11-13T09:22:32.338Z',
		"name": 'Navneethan Pillai ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/navneethan-pillai-ab9b53229',
		"instagramProfile": '_._navneethan_.___',
		"facebookProfile": 'https://www.facebook.com/navneethan.pillai',
		"twitterProfile":
			'https://twitter.com/Navneethan_5320?t=pvKTn0cZ6MjT2SuHXbXhzQ&s=08',
		"photo": 'https://drive.google.com/uc?export=view&id=1PWGtuyoEweIw_c85sF1uVB9A2HW4qnXI',
	},
	{
		"S_no":"28",
		"timestamp": '2022-11-13T11:26:03.238Z',
		"name": 'Rajkumar Majhi ',
		"year": '2nd',
		"vertical": ' Graphic Designer',
		"linkedinProfile": 'https://www.linkedin.com/in/rajkumar-majhi-1278b5226',
		"instagramProfile": 'https://www.instagram.com/art_by_rajkumar/',
		"facebookProfile":
			'https://m.facebook.com/rajkumar.majhi.5473894?eav=AfbphBhB888-yGDiqJl4t4-QfpENKHJKT0WY0Xmr9X35cYVqp6U_BnfL3GZAbsSHodU&ref_component=mbasic_home_header&ref_page=%2Fwap%2Fhome.php&refid=8&paipv=0',
		"twitterProfile":
			'https://twitter.com/Rajkumar__majhi?t=gL5nThuKTIRCqGlmiJC2Rg&s=09',
		"githubProfile": 'https://github.com/rajkumarmajhi31',
		"photo": 'https://drive.google.com/uc?export=view&id=18gq2S_oNTloJ_d_ma0scDRviKkqvC56b',
	},
	{
		"S_no":"29",
		"timestamp": '2022-11-14T04:58:21.282Z',
		"name": 'Rama Bhala',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/rama-bhala-84143a224',
		"photo": 'https://drive.google.com/uc?export=view&id=1ArN_JxLgjoXR3giHCxpLWs65VRcaGdOJ',
	},
	{
		"S_no":"30",
		"timestamp": '2022-11-13T09:48:04.673Z',
		"name": 'Rudraksh',
		"year": '2nd',
		"vertical": 'Graphic Designer',
		"linkedinProfile": 'https://www.linkedin.com/in/rudraksh-rajput-60249b244',
		"instagramProfile": 'rudr_aksh2002',
		"photo": 'https://drive.google.com/uc?export=view&id=1Uocxd82St3FVYWyHfmFgU1pYgr_9UhsW',
	},
	{
		"S_no":"31",
		"timestamp": '2022-11-13T16:43:13.570Z',
		"name": 'Saiyam Saxena',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/saiyam-saxena-b28961241/',
		"instagramProfile": 'https://www.instagram.com/saiyam_saxena/',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100007095016924',
		"twitterProfile": 'https://twitter.com/SaiyamSaxena',
		"githubProfile": 'https://github.com/Saiyam10',
		"photo": 'https://drive.google.com/uc?export=view&id=1kn0xPtbxFJYUgdUuu-Q6yKQBnIV0oQSz',
	},
	{
		"S_no":"32",
		"timestamp": '2022-11-13T14:33:41.046Z',
		"name": 'Samyukta alawa',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/samyukta-alawa-1785ba245',
		"instagramProfile": ' _samyukta_25',
		"facebookProfile": '-',
		"twitterProfile": '-',
		"githubProfile": '-',
		"photo": '../assets/team_img/Team__Download/samyukta.jpeg',
	},
	{
		"S_no":"33",
		"timestamp": '2022-11-13T11:00:57.770Z',
		"name": 'Sania Zehra Rizvi ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/sania-zehra-rizvi-6b7a95244',
		"instagramProfile": 'https://instagram.com/_.sa.n.ia._?igshid=YmMyMTA2M2Y=',
		"photo": 'https://drive.google.com/uc?export=view&id=1hSJJZ6_RtbesLJrhIUaMSkH1ZNXFWt_J',
	},
	{
		"S_no":"34",
		"timestamp": '2022-11-14T08:33:38.058Z',
		"name": 'Sanidhya Vijay',
		"year": '2nd',
		"vertical": 'Graphic Designer',
		"linkedinProfile": 'https://www.linkedin.com/in/sanidhya-vijay-02b183229',
		"instagramProfile":
			'https://www.instagram.com/invites/contact/?i=artry4wm730f&utm_content=22347mn',
		"photo": 'https://drive.google.com/uc?export=view&id=1jSh43dQuRIUfE1sKW7pyqHmRd9zG9mwL',
	},
	{
		"S_no":"35",
		"timestamp": '2022-11-14T04:55:14.755Z',
		"name": 'Sanya Arora ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/sanya-arora-228212241',
		"photo": 'https://drive.google.com/uc?export=view&id=1LjxSVshH382ac28eF2N3mYuaoQYNOXRy',
	},
	{
		"S_no":"36",
		"timestamp": '2022-11-13T21:02:46.815Z',
		"name": 'Shailee Gavnekar ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/shailee-gavnekar-32b780233',
		"instagramProfile":
			'https://instagram.com/shailee_gavnekar27?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100083231649592',
		"twitterProfile":
			'https://twitter.com/GavnekarShailee?t=SOxijlZ8BsR6knG3eFU3Dg&s=08',
		"photo": 'https://drive.google.com/uc?export=view&id=1ci1KvIxcPNDnEMQ5TrFgShqC1spv1BAl',
	},
	{
		"S_no":"37",
		"timestamp": '2022-11-13T12:09:26.871Z',
		"name": 'Suhaani Batra',
		"year": '2nd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/suhaani-batra-842858244/',
		"instagramProfile": 'https://www.instagram.com/suhaanii.batra/',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100082825976960',
		"twitterProfile": 'https://twitter.com/BatraSuhaani',
		"githubProfile": 'https://github.com/suhaanibatra',
		"photo": 'https://drive.google.com/uc?export=view&id=1ajCMFQgeHtMMS_z_Ossra4rxDp9E1rME',
	},
	{
		"S_no":"38",
		"timestamp": '2022-11-13T14:14:38.134Z',
		"name": 'Suhani Jain ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/suhani-jain-b96800239',
		"instagramProfile": 'https://instagram.com/accio_oo9?igshid=YmMyMTA2M2Y=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100082908894329',
		"twitterProfile":
			'https://twitter.com/Accio5406?t=WpN-jTH8WSjeOILYm_ud-Q&s=09',
		"photo": 'https://drive.google.com/uc?export=view&id=12W2ESEJgY90xWVdwX7UpxaR7rCwJi9DY',
	},
	{
		"S_no":"39",
		"timestamp": '2022-11-13T09:31:02.305Z',
		"name": 'Suyash Tiwari ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/suyash-tiwari-8b1910244',
		"instagramProfile": 'suyash09tiwari',
		"facebookProfile": 'Suyash Tiwari ',
		"photo": 'https://drive.google.com/uc?export=view&id=188R4GISphXtnqN3LxjJfvNoErHswYMyw',
	},
	{
		"S_no":"40",
		"timestamp": '2022-11-13T14:32:21.947Z',
		"name": 'Uday Pratap Singh ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/uday-pratap-singh-857869229',
		"instagramProfile": 'the_bfg__',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100083295217122',
		"photo": 'https://drive.google.com/uc?export=view&id=13iHvYY7zFcZfCjjNFanYj5JPWRAIRtas',
	},
	{
		"S_no":"41",
		"timestamp": '2022-11-13T22:46:27.344Z',
		"name": 'Vidit Purohit ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/vidit-purohit-36b538231',
		"instagramProfile":
			'https://instagram.com/vidit01purohit?igshid=YmMyMTA2M2Y=',
		"photo": '../assets/team_img/Team__Download/vidit.jpeg',
	},
	{	
		"S_no":"42",
		"timestamp": '2022-11-13T10:17:01.027Z',
		"name": 'Zoheb Hasan ',
		"year": '2nd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/zoheb-hasan-74a35a231',
		"facebookProfile": 'https://www.facebook.com/zoheb.hasan.106',
		"photo": 'https://drive.google.com/uc?export=view&id=11RI24AF463XQ5SawsacXnvwHjQyS_X8s',
	},
	{
		"S_no":"43",
		"timestamp": '2022-11-13T18:08:01.052Z',
		"name": 'Abhishek Nagar ',
		"year": '3rd',
		"vertical": ' Senior Web Developer',
		"linkedinProfile": 'https://www.linkedin.com/in/abhishek-nagar-5353971ba',
		"instagramProfile": 'https://www.instagram.com/abhisheknagar0110',
		"githubProfile": 'https://github.com/Officialabhishek',
		"photo": 'https://drive.google.com/uc?export=view&id=1xijEH082yxjOvX11SxXNx_9GQ_SvwFDq',
	},
	{
		"S_no":"44",
		"timestamp": '2022-11-13T18:17:00.125Z',
		"name": 'Abhishek Raghuwanshi ',
		"year": '3rd',
		"vertical": 'Head Public Relation',
		"linkedinProfile":
			'https://www.linkedin.com/in/abhishek-raghuwanshi-921265218',
		"photo": 'https://drive.google.com/uc?export=view&id=17YPc3IOvIwThJacTFeD71DqTNCZXCo_V',
	},
	{
		"S_no":"45",
		"timestamp": '2022-11-14T07:55:37.461Z',
		"name": 'Animesh Nayak',
		"year": '3rd',
		"vertical": "Students' Jt. General Secretary (Administration",
		"linkedinProfile": 'https://www.linkedin.com/in/animesh-nayak-8ba7b5218/',
		"instagramProfile": 'https://www.instagram.com/istemanit/?hl=en',
		"photo": 'https://drive.google.com/uc?export=view&id=1mVVe90cQQ6pU9UYsRpYbz0ofmDVK3Ght',
	},
	{
		"S_no":"46",
		"timestamp": '2022-11-14T10:57:43.584Z',
		"name": 'Anoushka Gupta',
		"year": '3rd',
		"vertical": 'Head Media and Publicity',
		"linkedinProfile": 'https://www.linkedin.com/in/anoushka-gupta-1b9124218',
		"instagramProfile": 'https://www.instagram.com/_anoushka_57_/',
		"photo": 'https://drive.google.com/uc?export=view&id=1gzZPjnYCxPOGbJOd0Q76ibqj6NYw41Ud',
	},
	{
		"S_no":"47",
		"timestamp": '2022-11-13T18:05:58.666Z',
		"name": 'Avni Chanderia',
		"year": '3rd',
		"vertical": 'Head General Affairs',
		"linkedinProfile": 'https://www.linkedin.com/in/avni-chanderia/',
		"instagramProfile": 'https://www.instagram.com/avni.cc/',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100064265820847',
		"photo": 'https://drive.google.com/uc?export=view&id=1G2O0fHBnkHaaC9gGihITSbXxptFtm4JT',
	},
	{
		"S_no":"48",
		"timestamp": '2022-11-14T04:59:07.640Z',
		"name": 'Ayush Ram Tiwari',
		"year": '3rd',
		"vertical": 'Head Operations & Logistics',
		"linkedinProfile": 'https://www.linkedin.com/in/ayush-ram-tiwari',
		"instagramProfile": 'https://www.instagram.com/hayy_ram_/',
		"photo": 'https://drive.google.com/uc?export=view&id=105TTmpgDU__UBMH1rCSwKHLSMV9mR8Dl',
	},
	{
		"S_no":"49",
		"timestamp": '2022-11-13T18:11:55.805Z',
		"name": 'Danisha Raj',
		"year": '3rd',
		"vertical": 'Head of Sponsorship and Marketing',
		"linkedinProfile": 'https://www.linkedin.com/in/danisha-raj-711622202',
		"instagramProfile": 'https://instagram.com/ahsinad_raj?igshid=ZDdkNTZiNTM=',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100070336119491',
		"photo": '../assets/team_img/DanishaRaj.jpg',
	},
	{
		"S_no":"50",
		"timestamp": '2022-11-14T11:25:42.534Z',
		"name": 'Harsha Arora',
		"year": '3rd',
		"vertical": 'Quizzing Head',
		"linkedinProfile": 'https://www.linkedin.com/in/harsha-arora-89b020218',
		"instagramProfile": '@heyyharsha',
		"photo": 'https://drive.google.com/uc?export=view&id=1VmBtLIwX9oZ-uxy0zMlNaCfJAUsN1BH_',
	},
	{
		"S_no":"51",
		"timestamp": '2022-11-14T18:09:28.062Z',
		"name": 'Jatin Chhattani ',
		"year": '3rd',
		"vertical": 'Team member',
		"linkedinProfile": 'https://www.linkedin.com/in/jatin-chhattani-666285219',
		"instagramProfile":
			'https://instagram.com/jatinchhattani?igshid=ZDdkNTZiNTM=',
		"photo": '../assets/team_img/Team__Download/jatin.jpg',
	},
	{
		"S_no":"52",
		"timestamp": '2022-11-14T04:14:42.673Z',
		"name": 'Kartik Gupta ',
		"year": '3rd',
		"vertical": 'Head of Team Management',
		"linkedinProfile": 'https://www.linkedin.com/in/kartik-gupta-46bb88202',
		"photo": 'https://drive.google.com/uc?export=view&id=17bANQ3sOj9fQS841hydl4TZBPl6TNl5u',
	},
	{
		"S_no":"53",
		"timestamp": '2022-11-13T18:28:15.915Z',
		"name": 'Navyasree Konagalla',
		"year": '3rd',
		"vertical": 'Jt. General Secretary (Events ',
		"linkedinProfile":
			'https://www.linkedin.com/in/navyasree-konagalla-281314203',
		"instagramProfile": 'https://instagram.com/nav.yeahhh?igshid=ZDdkNTZiNTM=',
		"photo": 'https://drive.google.com/uc?export=view&id=1t_vyJNV3el7GI5uFV6MLgtzFTrk0b2PE',
	},
	{
		"S_no":"54",
		"timestamp": '2022-11-14T10:19:25.123Z',
		"name": 'Nikunj Aagar',
		"year": '3rd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/nikunj-aagar-06272',
		"instagramProfile": 'https://instagram.com/nikunjaagar786',
		"facebookProfile": 'https://www.facebook.com/nikunj.aagar',
		"twitterProfile": 'https://twitter.com/nikunj_aagar',
		"photo": 'https://drive.google.com/uc?export=view&id=15qi6jeq7u3gA4yciP3rNY1npOLKcMxqr',
	},
	{
		"S_no":"56",
		"timestamp": '2022-11-14T10:47:50.863Z',
		"name": 'Nirupam Gupta ',
		"year": '3rd',
		"vertical": 'Executive ',
		"linkedinProfile": 'https://www.linkedin.com/in/nirupam-gupta-a18553218',
		"photo": 'https://drive.google.com/uc?export=view&id=1w9nfN0bvY1JV_X5zrN2HIYYfSjzW_wj-',
	},
	{
		"S_no":"57",
		"timestamp": '2022-11-14T10:45:35.177Z',
		"name": 'Nupur Prajapati ',
		"year": '3rd',
		"vertical": 'Head of Content',
		"linkedinProfile": 'www.linkedin.com/in/nupur-prajapati-b75552218',
		"instagramProfile": 'https://www.instagram.com/nupur.prajapati.982',
		"facebookProfile": 'https://www.facebook.com/nupur.prajapati.982',
		"photo": 'https://drive.google.com/uc?export=view&id=1A3GDarrHLH0vZVH4pln1DCJCL7RR6_yu',
	},
	{
		"S_no":"58",
		"name": 'Vibhuti Deshmukh',
		"year": '3rd',
		"vertical": 'Head Finance',
		"linkedinProfile": 'https://www.linkedin.com/in/vibhuti-deshmukh-b9694920a/',
		"instagramProfile": 'https://www.instagram.com/vibs.____/',
		"facebookProfile": 'https://www.facebook.com/vibhuti.deshmukh.104',
		"photo": '../assets/team_img/Team__Download/vibhuti.jpg',
	},
	{
		"S_no":"59",
		"timestamp": '2022-11-14T08:16:51.921Z',
		"name": 'Pradhuman Mahor',
		"year": '3rd',
		"vertical": 'Head Public Relation',
		"linkedinProfile": 'https://www.linkedin.com/in/pradhuman-mahor-bbaa46204 ',
		"instagramProfile": 'https://www.instagram.com/pradhuman__gupta/ ',
		"photo": '../assets/team_img/Team__Download/pradhuman.jpeg',
	},
	{
		"S_no":"60",
		"timestamp": '2022-11-13T18:21:59.228Z',
		"name": 'Pranav Garg',
		"year": '3rd',
		"vertical": 'Team Manager',
		"linkedinProfile": 'https://www.linkedin.com/in/pranav-garg-186292206',

		"githubProfile": 'https://github.com/Pranav-Garg5',
		"photo": 'https://drive.google.com/uc?export=view&id=1RhN26ouZssXEZxPq88Sj4Oh9xNi1JgH-',
	},
	{
		"S_no":"61",
		"timestamp": '2022-11-13T18:01:59.621Z',
		"name": 'Ravuri Nikhil',
		"year": '3rd',
		"vertical": 'Video editor',
		"linkedinProfile": 'https://www.linkedin.com/in/ravuri-nikhil-981a331a5',
		"photo": '../assets/team_img/Team__Download/IMG_20221106_200854 - Brain Genix.jpg',
	},
	{	
		"S_no":"62",
		"timestamp": '2022-11-14T10:58:23.281Z',
		"name": 'Shilpee Agrawal',
		"year": '3rd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/shilpee-agrawal/',
		"instagramProfile": 'https://www.instagram.com/gourii_i/',
		"facebookProfile": 'https://www.facebook.com/shilpiagrawal.agrawal.581/',
		"photo": 'https://drive.google.com/uc?export=view&id=1m-yvmzrY4FeMsy5ZJabuK9yLjnF_FXXd',
	},
	{
		"S_no":"63",
		"timestamp": '2022-11-14T15:52:30.648Z',
		"name": 'Shubh Asati',
		"year": '3rd',
		"vertical": 'Head Technical',
		"linkedinProfile": 'https://www.linkedin.com/in/shubh-asati/',
		"githubProfile": 'https://github.com/shubhtrikal',
		"photo": 'https://drive.google.com/uc?export=view&id=1Mckp_HeLROZtLPnG5qXahRKGGyjbeQAe',
	},
	{
		"S_no":"64",
		"timestamp": '2022-11-14T03:59:41.664Z',
		"name": 'Soumya Agrawal ',
		"year": '3rd',
		"vertical": 'Quizzing',
		"linkedinProfile": 'https://www.linkedin.com/in/soumya-agrawal-ab1984202',
		"instagramProfile": 'https://www.instagram.com/soumyx._.agrawal/?hl=en',
		"twitterProfile": 'https://twitter.com/Soumy_16',
		"photo": 'https://drive.google.com/uc?export=view&id=1ELyDkEBpZDBuyNpMl9kYFzaom4GaMOfO',
	},
	{
		"S_no":"65",
		"timestamp": '2022-11-14T15:54:43.251Z',
		"name": 'Tushar Gehlot',
		"year": '3rd',
		"vertical": 'Head Web Operations',
		"linkedinProfile": 'https://www.linkedin.com/in/tushar-gehlot-50502420a/',
		"githubProfile": 'https://github.com/22tushar',
		"photo": 'https://drive.google.com/uc?export=view&id=1kajCOnQzlFK84IigBnrhskHpjC-S4HwO',
	},
	{
		"S_no":"66",
		"timestamp": '2022-11-14T08:13:19.876Z',
		"name": 'Vishesh Chhaperwal',
		"year": '3rd',
		"vertical": 'Executive',
		"linkedinProfile": 'https://www.linkedin.com/in/vishesh-chhaperwal-380a231b9',
		"instagramProfile": 'https://instagram.com/vshesh_25?igshid=YmMyMTA2M2Y=',
		"photo": 'https://drive.google.com/uc?export=view&id=1xFhvjJJcJGTXvLkFUEGvcg6V4hxO4J_0',
	},
	{
		"S_no":"67",
		"timestamp": '2022-11-14T10:22:51.879Z',
		"name": 'Yuvraj Singh Rajput ',
		"year": '3rd',
		"vertical": 'Head of Sponsorship and Marketing ',
		"linkedinProfile": 'linkedin.com/in/yuvraj-singh-rajput-8a77a3210',
		"instagramProfile": 'https://www.instagram.com/sinyuvi_/',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100052119575518',
		"photo": '../assets/team_img/Team__Download/yuvraj.jpg',
	},
	{
		"S_no":"68",
		"timestamp": '2022-11-14T12:14:33.077Z',
		"name": 'Akanksha Gupta',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/akanksha-gupta-nitb/',
		"instagramProfile": 'https://www.instagram.com/akanksha_94154/',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Akanksha%20-%20Akanksha%20Gupta%20updated11.jpeg',
	},
	{
		"S_no":"70",
		"timestamp": '2022-11-14T11:57:51.399Z',
		"name": 'Akshama Dubey',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/akshma-dubey-9a60031b7',
		"facebookProfile": 'https://www.facebook.com/akshma.dubey',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/20210330_180504%20-%20Akshma%20Dubey%20updated.jpg',
	},
	{
		"S_no":"71",
		"timestamp": '2022-11-14T12:04:46.118Z',
		"name": 'Akshat Jain',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/ak2shat',
		"instagramProfile": 'https://www.instagram.com/ak2shat/',
		"twitterProfile": 'https://mobile.twitter.com/SsJain_akshat',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210929_174716%20-%20Akshat%20Jain%20updated.jpg',
	},
	{
		"S_no":"72",
		"timestamp": '2022-11-14T11:44:10.476Z',
		"name": 'Akshay Pandey',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/akshay-pandey-310101/',
		"githubProfile": 'https://github.com/imakshay31',
	},
	{
		"S_no":"73",
		"timestamp": '2022-11-14T11:39:11.937Z',
		"name": 'Aman Malviya',
		"year": '4th',
		"vertical": 'Treasurer',
		"linkedinProfile":
			'https://www.linkedin.com/in/aman-kumar-malviya-5347871b1/',
		"instagramProfile": 'https://www.instagram.com/aman_malviya._/',
		"facebookProfile": 'https://www.facebook.com/aman.malviya.9699523',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/-hxipo2%20-%20Aman%20Malviya.jpg',
	},
	{
		"S_no":"74",
		"timestamp": '2022-11-14T11:32:08.401Z',
		"name": 'Ananya Rawat',
		"year": '4th',
		"vertical": "Student's Vice-Chairperson(Events",
		"linkedinProfile": 'https://www.linkedin.com/in/ananya-rawat-010a711b5/',
		"instagramProfile":
			'https://www.instagram.com/annanya_rawat_/?utm_medium=copy_link',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20211003_001543%20-%20Ananya%20Rawat.jpg',
	},
	{
		"S_no":"76",
		"timestamp": '2022-11-14T12:08:08.039Z',
		"name": 'Ankit Gupta',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/ankit-gupta-005b5819a',
		"facebookProfile": 'https://www.facebook.com/ankitgupta',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210831_120451_403%20-%20Ankit%20Gupta.jpg',
	},
	{
		"S_no":"77",
		"timestamp": '2022-11-14T11:45:27.434Z',
		"name": 'Ayush Rusia',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/ayushrusia/',
		"githubProfile": 'https://github.com/AyushRusia',
	},
	{
		"S_no":"78",
		"timestamp": '2022-11-14T11:46:58.388Z',
		"name": 'Digant Maheshwari',
		"year": '4th',
		"vertical": "Student's Chairperson",
		"linkedinProfile": '#',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG-20210808-WA0108%20-%20Digant%20Maheshwari%20updated11.jpg',
	},
	{
		"S_no":"79",
		"timestamp": '2022-11-14T11:53:04.159Z',
		"name": 'Divyanshu Shukla',
		"year": '4th',
		"vertical": "Student's Co-Convener",
		"linkedinProfile": 'http://www.linkedin.com/in/divyanshu-shukla-s7',
		"instagramProfile": 'https://www.instagram.com/divyanshu_s7/?hl=en',
		"facebookProfile": 'https://www.facebook.com/divyanshushuklazz10',
		"twitterProfile": 'https://twitter.com/divyans23283529',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_divyanshu%20new.jpg',
	},
	{
		"S_no":"80",
		"timestamp": '2022-11-14T11:41:10.445Z',
		"name": 'Faisal Jamil',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/faisaljamil25/',
		"githubProfile": 'https://github.com/faisaljamil25',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Faisal%20Jamil%20-%20Faisal%20Jamil.png',
	},
	{
		"S_no":"81",
		"timestamp": '2022-11-14T11:56:26.992Z',
		"name": 'Hrishank Soni',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/hrishank-soni-5922a01b5',
		"instagramProfile": 'https://www.instagram.com/hrishank619/',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100005695638812',
		"twitterProfile": 'https://twitter.com/Hrishanksoni09?s=08',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Screenshot_2021-10-03-13-02-07-66%20-%20Hrishank%20Soni.jpg',
	},
	{
		"S_no":"82",
		"timestamp": '2022-11-14T11:51:18.458Z',
		"name": 'Hussain Manasi',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/hussain-manasi/',
		"instagramProfile": 'https://www.instagram.com/hugh_sane/',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Head%20shot%20-%20Hussain%20Manasi%20updated.jpg',
	},
	{
		"S_no":"83",
		"timestamp": '2022-11-14T11:54:52.213Z',
		"name": 'Jitesh Kejriwal',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": '#',
	},
	{
		"S_no":"84",
		"timestamp": '2022-11-14T11:48:34.301Z',
		"name": 'Kalyani Singh Bais',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/kalyani-singh-bais-6220541b0',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/20210904_154633-01%20-%20Kalyani%20Singh%20Bais%20updated11.jpeg',
	},
	{
		"S_no":"85",
		"timestamp": '2022-11-14T12:06:58.616Z',
		"name": 'Mrattunjaya Trivedi',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile":
			'https://www.linkedin.com/in/mrattunjaya-trivedi-6389091b6',
		"instagramProfile": 'ttps://www.instagram.com/_mrityu_n_jai/',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Mrattunjaya%20Trivedi%20-%20Mrittunjay%20trivedi%20updated.jpg',
	},
	{
		"S_no":"86",
		"timestamp": '2022-11-14T12:05:42.885Z',
		"name": 'Prashant Kaushal',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": '#',
	},
	{
		"S_no":"87",
		"timestamp": '2022-11-14T12:09:32.816Z',
		"name": 'Pratyush Lokhande',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'http://www.linked.com/in/pratyushlokhande',
		"instagramProfile": 'http://www.instagram.com/pratyushlokhande',
		"facebookProfile": 'https://www.facebook.com/pratyushkumarlokhande',
		"twitterProfile": 'https://www.twitter.com/pratyuuuush',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/pratyush_lokhande%20-%20Pratyush%20Lokhande.jpg',
	},
	{
		"S_no":"88",
		"timestamp": '2022-11-14T11:55:23.819Z',
		"name": 'Rounak Sartaliya',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": '#',
	},
	{
		"S_no":"89",
		"timestamp": '2022-11-14T12:10:55.470Z',
		"name": 'Sanskar Yadav',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/sanskar-yadav-586b821b2',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210629_212828_921%20-%20Sanskar%20Yadav.jpg',
	},
	{
		"S_no":"90",
		"timestamp": '2022-11-14T12:03:17.651Z',
		"name": 'Satvika Singh',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/satvika-singh-58433a188',
		"instagramProfile": 'https://www.instagram.com/satvikasingh024/',
		"facebookProfile": 'https://www.facebook.com/satvika.singh.5439',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/Satvika%20-%20satvika%20singh.jpg',
	},
	{	
		"S_no":"91",
		"timestamp": '2022-11-14T11:49:47.351Z',
		"name": 'Shubh Mishra',
		"year": '4th',
		"vertical": "Student's Convener",
		"linkedinProfile": '#',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/shubh.jpg',
	},
	{
		"S_no":"92",
		"timestamp": '2022-11-14T11:54:08.909Z',
		"name": 'Siddharth Shrivastava',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": '#',
	},
	{
		"S_no":"93",
		"timestamp": '2022-11-14T12:02:05.487Z',
		"name": 'Spoorthi Talikonda',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": '#',
	},
	{
		"S_no":"94",
		"timestamp": '2022-11-14T11:25:45.569Z',
		"name": 'Tushar Khajuria',
		"year": '4th',
		"vertical": "Student's Vice-Chairperson(Administration",
		"linkedinProfile": 'https://www.linkedin.com/in/tushar-khajuria-042397179/',
		"instagramProfile": 'https://www.instagram.com/_tusharkhajuria_/',
		"facebookProfile": 'https://www.facebook.com/tushar.khajuria.1200',
		"twitterProfile": 'https://twitter.com/Tushar_K12?s=09',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210320_145950_tushar%20updated11.jpg',
	},
	{
		"S_no":"95",
		"timestamp": '2022-11-14T12:12:10.485Z',
		"name": 'Vaishnavi Gupta',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/vaishnavi-gupta-2927881aa',
		"facebookProfile": 'https://www.facebook.com/profile.php?id=100037349440333',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210822_122821-01~2%20-%20Vaishnavi%20Gupta.jpeg',
	},
	{
		"S_no":"96",
		"timestamp": '2022-11-14T12:13:03.487Z',
		"name": 'Vartika Singh',
		"year": '4th',
		"vertical": 'Core Team Member',
		"linkedinProfile": 'https://www.linkedin.com/in/vartika-sharma-a921631b8',
		"photo":
			'https://raw.githubusercontent.com/ISTE-SC-MANIT/ISTE-assets/master/team-images/images2023/IMG_20210728_223426%20-%20vartika%20sharma%20updated.jpg',
	},
]